# single zookeeper, single kafka borker, local flink cluster
version: '3.3'
services:
  zookeeper:
    container_name: single-zookeeper
    image: zookeeper:3.4.10
    ports:
      - '2181:2181'
  kafka:
    container_name: single-kafka
    image: wurstmeister/kafka:0.10.2.1
    links:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.6
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: topic1:1:1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  flink:
    container_name: local-flink-cluster
    image: flink:1.3.1-hadoop26-scala_2.11
    command: local
    ports:
      - '8081:8081'
